title: Kasidid Yookong
# logo: /assets/my_img.jpg
description: NisitID 6530200576 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
